### ISSUE TITLE
Spaces in filename converted to "+" symbol

### ISSUE THREAD

**Issue by girogiacomo** [4ndv/magnets#1]
Hello,
I just noticed that your tool converts spaces in "+" symbols...
It should convert them in "%20" to be the right char in the magnet link
Otherwise very cool tool!

![immagine](https://github.com/4ndv/magnets/assets/39419444/6ff74ff3-c49a-4b45-b8f6-a62f38fb7d97)

**Comment by 4ndv** [comment]
Hi! Clients actually should be able to handle both variants, since "+" signs explicitly used as a "space" in the early magnet link specification: https://magnet-uri.sourceforge.net/magnet-draft-overview.txt

**Comment by girogiacomo** [comment]
I only noticed it because I had this problem with the web interface of Transmission... it added + instead of adding a space...

I deleted it before it could download the metadata though... so it could differ

Sorry for my broken English but today has been a veeery long day 😅

**Comment by 4ndv** [comment]
Your client will anyway try to fetch torrent metadata using DHT, which will contain actual name, so that's would not be an issue with non-conforming clients
