### ISSUE TITLE
Request to Add Trackers from NewTrackon 

### ISSUE THREAD

**Issue by xxcriticxx** [4ndv/magnets#2]
@4ndv Could you please add trackers from https://newtrackon.com/list to your project?

**Comment by 4ndv** [comment]
Hi! Do I understand correctly that primary reason for implementing it alongside trackerslist is that it monitors uptime of the trackers?

I'll check if we can call its APIs from the client-side

**Comment by xxcriticxx** [comment]
You are correct. In my opinion, NewTrackon is very similar to Trackerslist.

**Comment by 4ndv** [comment]
Done! Had to do some reordering of buttons to fit it all in a single line on desktop, feel free to reopen this issue (or open a new one) if you notice any problems

**Comment by xxcriticxx** [comment]
Nice job. Thank you!
